---
- name: update timezone
  shell: dpkg-reconfigure --frontend noninteractive tzdata

- name: update system locale
  shell: >
    /usr/sbin/update-locale LANG={{ debian_base_locales[0] }} LANGUAGE={{ debian_base_lang }}

- name: restart ntp
  service:
    name=ntp
    state=restarted
    enabled=yes

- name: restart sshd service
  service:
    name=ssh
    state=restarted
    enabled=yes
